config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { minimum: 1, maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post was created successfully."
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post was updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def confirm
    @post = Post.new(post_params)
    render :new if @post.invalid?
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li><a href="#">Twitter Clone</a></li>
      </ul>
    </header>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <footer>
      <p>© 2021, Twitter Clone.</p>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <h3>The following errors prevented the post from being saved.</h3>
  <ul id="message">
    <% @post.errors.full_messages.each do |msg| %>
       <%= msg %>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @post, local: true, url: confirm_posts_path) do |f| %>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/posts/confirm.html.erb
<h3>Send with the following contents.</h3>
<%= form_with(model: @post, local: true) do |f| %>

    <%= f.hidden_field :content %>

    <p>Text:<%= @post.content %></p>

    <%= f.submit "register" %>

<% end %>

<p><%= link_to 'Return', :back %></p>

app/views/posts/edit.html.erb
<h1>Edit Tweet</h1>

<%= render 'form' %>

<%= link_to 'Cancel and return to tweets listing', posts_path %>

app/views/posts/index.html.erb
<h1>Tweets listing page</h1>

<table class="table">
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td class="content"><%= post.content %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'List', post_path(post) %></td>
        <td><%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Create new tweet', new_post_path %>
</p>

app/views/posts/new.html.erb
<h1>Create a new tweet</h1>

<%= render 'form' %>

<%= link_to 'Return to tweet listing', posts_path %>

app/views/posts/show.html.erb
<h1>Showing tweet Details</h1>

<p><strong>Content: </strong> <%= @post.content %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %> |
<%= link_to 'Return to tweets listing', posts_path %>